### ISSUE TITLE
JIT compiler unavailable after running storybook build

### ISSUE THREAD

**Issue by Carlodeboer** [brandonroberts/angular-v17-vite-storybook#10]
Hi guys,

First of all thanks for the work you're doing on this project!

Have you got any idea why I'm getting a `JIT compiler unavailable` after running `build-storybook` and opening `storybook-static/index.html`?

Thanks in advance!

**Comment by brandonroberts** [comment]
Probably because its forced to JIT mode when you do a build here https://github.com/brandonroberts/angular-v17-vite-storybook/blob/main/.storybook/main.ts#L42 

Try setting `jit: false` and run a storybook build and see if it works.

**Comment by Carlodeboer** [comment]
Hi Brandon,

Thanks for getting back to me! 

I've tried setting jit to false, which results in 
`Error: Cannot read properties of undefined (reading 'selector')` when I open a story. Do you experience the same issue?

**Comment by brandonroberts** [comment]
Oh, right. Storybook has to run in JIT mode, which needs the `@angular/compiler` to be loaded first. Need to see where the proper place to put it early enough
