### ISSUE TITLE
[Feature Request]: Integrate Compodoc for generating documentation.

### ISSUE THREAD

**Issue by codexshell** [brandonroberts/angular-v17-vite-storybook#2]
## What is the problem this feature would solve
It would allow for the generation of documentation when viewing stories.

## What is the feature you are proposing to solve the problem?
I understand that the project is sill in the early stages of development and that the request may be premature.
I'd like to suggest integrating Compodoc (or a similar equivalent) for generating documentation for Angular components.

## What alternatives have you considered

Configuring Compodoc by borrowing from Webpack's configuration (use of `tsconfig.doc.json` and inclusion of the `preview.ts` file).
Having Compodoc run as a separate custom npm script.
I was able to achieve the desired result. It would be great to have `compodoc` to run on watch mode

**Comment by brandonroberts** [comment]
Closed by https://github.com/brandonroberts/angular-v17-vite-storybook/pull/3
