### ISSUE TITLE
 [Bug]: `componentWrapperDecorator` not working as expected.

### ISSUE THREAD

**Issue by codexshell** [brandonroberts/angular-v17-vite-storybook#4]
## Describe the bug
The issue is with the preview pane on a browser.
From the terminal no error is thrown and `Vite` builds successfully.
Linting the project also produces no errors (or warnings). 
![Screenshot](https://i.imgur.com/hgko9fw.png)

## To reproduce
Add `componentWrapperDecorator` as part of the `decorators` array on the `meta` object.

## System
![system info](https://i.imgur.com/Ou4Pr9J.png)

## Additional context

> Written with [StackEdit](https://stackedit.io/).

**Comment by brandonroberts** [comment]
You have to import from `@storybook/angular/dist/client` instead for some reason

**Comment by codexshell** [comment]
Hi,

Thank you so much for the swift response and the solution you provided. I appreciate the time and effort you took to help me resolve this issue. Your guidance was clear and very helpful.

I've implemented the solution, and everything is working perfectly now. I'm grateful for your support and the excellent work you're doing maintaining this project.

Best regards,
